# Generated by Django 3.1 on 2025-07-03 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('cuentascorrientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaPrecios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Remitos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('punto_de_venta', models.IntegerField()),
                ('numero', models.IntegerField()),
                ('bultos', models.IntegerField()),
                ('pesoaprox', models.DecimalField(decimal_places=2, max_digits=6)),
                ('valoraprox', models.DecimalField(decimal_places=2, max_digits=6)),
                ('impreso', models.BooleanField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuentascorrientes.clientes')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresa.sucursales')),
            ],
        ),
        migrations.CreateModel(
            name='RemitosDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=60)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=7)),
                ('importe_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dtounit', models.DecimalField(decimal_places=2, max_digits=6)),
                ('remito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuentascorrientes.remitos')),
            ],
        ),
    ]
