# Generated by Django 3.1 on 2025-08-23 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentascorrientes', '0003_auto_20250712_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estadoscc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=1)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='clientes',
            name='credito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='febaja',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='motivobaja',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='tolerancia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='estadoctacte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cuentascorrientes.estadoscc'),
        ),
    ]
