# Generated by Django 3.1 on 2025-08-30 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('cuentascorrientes', '0005_auto_20250829_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('alicuota_iva', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cuentascorrientes.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Procesos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuentascorrientes.procesos'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='empresa.sucursales'),
        ),
    ]
