# Generated by Django 3.1 on 2025-09-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentascorrientes', '0006_auto_20250830_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remitos',
            name='bultos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='remitos',
            name='impreso',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='remitos',
            name='pesoaprox',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='remitos',
            name='valoraprox',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
