# Generated by Django 3.1 on 2025-09-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentascorrientes', '0007_auto_20250903_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='remitosdet',
            name='alicuota_iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='remitosdet',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='remitosdet',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
