# Generated by Django 3.1 on 2025-09-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentascorrientes', '0008_auto_20250909_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='rm_realizado',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
