# Generated by Django 3.1 on 2025-09-29 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentascorrientes', '0009_pedidos_rm_realizado'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=4, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.BigIntegerField()),
                ('fecomp', models.DateField()),
                ('formulario', models.CharField(blank=True, max_length=10, null=True)),
                ('tipocomp', models.IntegerField()),
                ('sucucomp', models.IntegerField()),
                ('nrocomp', models.IntegerField()),
                ('importe', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('importe_iva', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('importe_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('alicuota_iva', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cuentascorrientes.clientes')),
                ('tipo_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cuentascorrientes.tiposdocumento')),
            ],
        ),
    ]
