# Generated by Django 3.1 on 2025-09-29 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentascorrientes', '0010_movimientos_tiposdocumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='tipo_documento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cuentascorrientes.tiposdocumento'),
            preserve_default=False,
        ),
    ]
