# Generated by Django 3.1 on 2025-10-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_auto_20250905_0149'),
        ('cuentascorrientes', '0011_clientes_tipo_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estadosped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=1)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Pedidos',
            new_name='PedidosTmp',
        ),
    ]
