# Generated by Django 3.1 on 2025-10-04 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentascorrientes', '0014_pedidos_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidosdet',
            old_name='precio',
            new_name='importe_unitario',
        ),
        migrations.RemoveField(
            model_name='pedidosdet',
            name='alicuota_iva',
        ),
    ]
