# Generated by Django 3.1 on 2025-10-04 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentascorrientes', '0015_auto_20251004_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidosdet',
            name='pedido',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='cuentascorrientes.pedidos'),
            preserve_default=False,
        ),
    ]
