# Generated by Django 3.1 on 2025-10-04 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentascorrientes', '0016_pedidosdet_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='rm_asociado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cuentascorrientes.remitos'),
        ),
    ]
