# Generated by Django 3.1 on 2025-10-07 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentascorrientes', '0018_auto_20251007_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remitosdet',
            name='remito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='cuentascorrientes.remitos'),
        ),
    ]
