# Generated by Django 3.1 on 2025-12-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentascorrientes', '0019_auto_20251007_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidostmp',
            name='edit_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
