# Generated by Django 3.1 on 2026-01-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentascorrientes', '0021_movimientos_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientos',
            name='tipocomp_str',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
