# Generated by Django 3.1 on 2026-02-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentascorrientes', '0022_movimientos_tipocomp_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientos',
            name='comprob_asoc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remitos',
            name='estado',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
