# Generated by Django 3.1 on 2026-03-15 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cuentascorrientes', '0023_auto_20260217_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoRemito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_aplicado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_aplicacion', models.DateTimeField(auto_now_add=True)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remitos_aplicados', to='cuentascorrientes.movimientos')),
                ('remito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_aplicados', to='cuentascorrientes.remitos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
