version: "2"
services:
  djlgcc:
    build: .
    container_name: djlgcc
    image: djlgcc:1.0
    environment:
      - DJANGO_SETTINGS_MODULE=djlgcc.settings
      - DEV=1
      - PYTHONUNBUFFERED=1
      - MYSQL_USER=root
      - MYSQL_PASSWORD=flash
      - MYSQL_HOST=mysqlserver
      - TZ=America/Argentina/Buenos_Aires
    ports:
      - 8007:8007
    volumes:
      - ./:/app
    command: python manage.py runserver 0.0.0.0:8007
    #command: tail -f /dev/null
    networks:
      - red_docker

networks:
    red_docker:
        external: true

