# Generated by Django 3.1 on 2025-09-05 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_datosusuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposComprobante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprobante', models.CharField(max_length=2)),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Comprobantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formulario', models.CharField(max_length=1)),
                ('punto_de_venta', models.IntegerField()),
                ('activo', models.BooleanField()),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresa.tiposcomprobante')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresa.sucursales')),
            ],
        ),
    ]
