# Generated by Django 3.1 on 2025-09-05 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_comprobantes_tiposcomprobante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiposcomprobante',
            old_name='comprobante',
            new_name='nombre',
        ),
    ]
